#!/bin/bash
#      +--------------------------------------------------------+
#      | WAVEWATCH IV, open source, code management by NOAA/NWS |
#      +--------------------------------------------------------+
#
# @file ww4_setup
# @brief Shell wrapper for the WAVEWATCH IV (WW4) setup tool.
# @details This script executes the underlying Python setup tool,
#          providing the recommended way to interactively configure
#          the active WW4 clone and compiler settings.
#
# Usage
# -----
# ww4_setup
#
# @copyright © 2026 National Weather Service, National Oceanic and Atmospheric
#               Administration. WAVEWATCH IV (TM) and WW4 (TM) are trademarks
#               of the National Weather Service.
# @author Aldgisl, Hendrik Tolman (Initial, 2026-03-24)
# @author Aldgisl, Hendrik Tolman (Last Update, 2026-03-30)
# @date 2026-03-30

# Get the directory of this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

python3 "$SCRIPT_DIR/ww4_setup.py" "$@"
